language: python
python:
- '2.7'
before_install:
- pip install cfn-pyplates
- pip install boto3
- pip install Jinja2
- pip install pytest-cov
install:
- pip install coveralls
script:
- coverage run --source=respawn/ setup.py test
- python setup.py install

after_success:
- coveralls
